### ISSUE TITLE
Custom commands

### ISSUE THREAD

**Issue by dzagu** [GAMMACASE/ServerRedirect#1]
Adding custom commands not work:
server_redirect_commands "sm_servers;sm_serv;sm_project;sm_list;sm_lis ta;sm_serwery;"
When I type !lista or sm_lista nothing happens.

**Comment by GAMMACASE** [comment]
You have an empty space here ``sm_lis ta``, so it's not gonna get registered properly, probably will add some checks for this one.

**Comment by dzagu** [comment]
I changed to this, and still same problem.
server_redirect_commands "sm_servers;sm_serwery;sm_project;sm_lista;sm_srv;"

**Comment by GAMMACASE** [comment]
did you restarted server after changing this in a config file?

**Comment by GAMMACASE** [comment]
alright, I think I found possible bug with this, gonna fix this in the next release

**Comment by GAMMACASE** [comment]
Are you able to compile plugin from master branch and check if this issue is fixed or not? Also thanks for the report!

**Comment by GAMMACASE** [comment]
This fix is in release now, check out 1.1.0 version. Reopen this issue if you'll experience it again.

**Comment by rajkodev** [comment]
Hey @GAMMACASE today installed, cfg file is setup properly, auto generated file in cfg/sourcemod is also there, but it looks like plugin doesn't running. When i type sm plugins I see plugin but there is no advertisements, and !servers doesnt work.

Also server is running under linux and sm 1.10
