### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by m1000rr** [GAMMACASE/ServerRedirect#10]
For some reason one of my servers throwing out these errors and plugin doesn't work there. 
What could be the reason?

`L 04/03/2020 - 09:00:40: [SM] Exception reported: Array index out-of-bounds (index -1, limit 32)
L 04/03/2020 - 09:00:40: [SM] Blaming: server_redirect.smx
L 04/03/2020 - 09:00:40: [SM] Call stack trace:
L 04/03/2020 - 09:00:40: [SM]   [1] Line 61, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\server_redirect.sp::ServerEntry::CutIp
L 04/03/2020 - 09:00:40: [SM]   [2] Line 371, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\server_redirect.sp::UpdateServersData
L 04/03/2020 - 09:00:40: [SM]   [3] Line 541, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\server_redirect.sp::SM_Servers`

**Comment by GAMMACASE** [comment]
Please take a look at this issue, #7.

**Comment by m1000rr** [comment]
Oh, had mistyped one of the server's  ip:port. Sorted now Thank You!
