### ISSUE TITLE
Auto redirect when server is full

### ISSUE THREAD

**Issue by Boogey1993** [GAMMACASE/ServerRedirect#12]
it would be nice if you could make that if the server is full that people automatically redirect to another server

**Comment by GAMMACASE** [comment]
This feature is not something that is suitable for this plugin imo, so don't think I'll ever add this.

**Comment by Boogey1993** [comment]
I think this feature would be amazing for it, because many communitys have full servers and if people join they just rediect too one of there other servers :)

**Comment by GAMMACASE** [comment]
As you said you need something like auto server redirect plugin, or something similar, this plugin adds absolutely different functionality, it allows players to view and connect to other servers via menu. So again you're asking for functionality that isn't suitable for this plugin imo. This plugin has very basic api that allows other to create something similar to what you are asking.

**Comment by Boogey1993** [comment]
> As you said you need something like auto server redirect plugin, or something similar, this plugin adds absolutely different functionality, it allows players to view and connect to other servers via menu. So again you're asking for functionality that isn't suitable for this plugin imo. This plugin has very basic api that allows other to create something similar to what you are asking.


take a look at this plugin, https://forums.alliedmods.net/showthread.php?t=322018
maybe you can implement it all in once :)

**Comment by GAMMACASE** [comment]
As I said I'm not currently looking into implementing this feature into this plugin, I'll leave this issue open until I finally decide if I'm going to implement this or not.
