### ISSUE TITLE
error after update csgo

### ISSUE THREAD

**Issue by dzagu** [GAMMACASE/ServerRedirect#15]
L 04/17/2020 - 12:01:02: [SM] Exception reported: [Server Redirect] Failed to create socket (13F6099C). [ip: 188.68.252.62:27016, errType: 6, errNum: 111]
L 04/17/2020 - 12:01:02: [SM] Blaming: server_redirect.smx
L 04/17/2020 - 12:01:02: [SM] Call stack trace:
L 04/17/2020 - 12:01:02: [SM]   [0] SetFailState
L 04/17/2020 - 12:01:02: [SM]   [1] Line 979, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\server_redirect.sp::SocketCreate_Error
L 04/17/2020 - 12:01:10: SourceMod error session started

**Comment by GAMMACASE** [comment]
This is already solved in master branch, not yet released tho.
