### ISSUE TITLE
server_redirect/net.sp(91) : error 139: could not find type "GameData"

### ISSUE THREAD

**Issue by am1github** [GAMMACASE/ServerRedirect#17]
We use SourceMod 1.10.0.6455 and get this error while compiling server_redirect.sp:

> server_redirect/net.sp(91) : error 139: could not find type "GameData"
> server_redirect/net.sp(96) : error 104: cannot find any methods for int
> server_redirect/net.sp(96) : warning 206: redundant test: constant expression is non-zero
> server_redirect/net.sp(96) : error 029: invalid expression, assumed zero
> server_redirect/net.sp(96) : error 029: invalid expression, assumed zero
> server_redirect/net.sp(96) : fatal error 190: too many error messages on one line

All requirements seems to fit:
- [latest socket.inc](https://github.com/JoinedSenses/sm-ext-socket/tree/master/scripting/include)
- [latest DHooks2](https://github.com/peace-maker/DHooks2/tree/dynhooks/sourcemod)

**Comment by GAMMACASE** [comment]
You also need sourcemod 1.10 includes for this to compile.
