### ISSUE TITLE
Unable To Create Socket

### ISSUE THREAD

**Issue by KillerRoi** [GAMMACASE/ServerRedirect#18]
server_redirect.smx (Server redirect): [Server Redirect] Failed to create socket (F7B10B8F). [ip: IP:PORT, errType: 4, errNum: 1]
![image](https://user-images.githubusercontent.com/54289708/81077286-6844b680-8f0a-11ea-9cf4-7834bb691a88.png)

**Comment by KillerRoi** [comment]
![image](https://user-images.githubusercontent.com/54289708/81077501-ae9a1580-8f0a-11ea-95e4-f7aa7f479430.png)

**Comment by GAMMACASE** [comment]
This problem is already "fixed" in master branch.
