### ISSUE TITLE
Exception reported: Client 21 is not connected

### ISSUE THREAD

**Issue by Z-RAY-Z** [GAMMACASE/ServerRedirect#19]
L 05/05/2020 - 15:27:20: [SM] Exception reported: Client 21 is not connected
L 05/05/2020 - 15:27:20: [SM] Blaming: server_redirect.smx
L 05/05/2020 - 15:27:20: [SM] Call stack trace:
L 05/05/2020 - 15:27:20: [SM]   [0] GetClientUserId
L 05/05/2020 - 15:27:20: [SM]   [1] Line 800, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\server_redirect.sp::ServerInfo_Menu

"Server redirect" (1.1.0) by GAMMA CASE

**Comment by GAMMACASE** [comment]
This issue is fixed in master branch.
