### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by Nanozke** [GAMMACASE/ServerRedirect#21]
L 05/15/2020 - 13:34:01: [SM] Exception reported: Can't find "CBaseServer::ProcessConnectionlessPacket" signature.
L 05/15/2020 - 13:34:01: [SM] Blaming: server_redirect.smx
L 05/15/2020 - 13:34:01: [SM] Call stack trace:
L 05/15/2020 - 13:34:01: [SM]   [0] SetFailState
L 05/15/2020 - 13:34:01: [SM]   [1] Line 24, server_redirect/redirect.sp::SetupDhooks
L 05/15/2020 - 13:34:01: [SM]   [2] Line 184, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\server_redirect.sp::OnPluginStart
L 05/15/2020 - 13:34:01: [SM]   [4] ServerCommandEx
L 05/15/2020 - 13:34:01: [SM]   [5] Line 402, D:\builds\build-sourcemod-msvc12\windows-1.10\build\plugins\basecommands.sp::Command_Rcon

L 05/15/2020 - 13:19:18: [SM] Exception reported: [Server Redirect] Failed to create socket (F88F0D50). [ip: 202.153.221.96:27016, errType: 6, errNum: 10061]
L 05/15/2020 - 13:19:18: [SM] Blaming: server_redirect.smx
L 05/15/2020 - 13:19:18: [SM] Call stack trace:
L 05/15/2020 - 13:19:18: [SM]   [0] SetFailState
L 05/15/2020 - 13:19:18: [SM]   [1] Line 979, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\server_redirect.sp::SocketCreate_Error
L 05/15/2020 - 13:19:59: [SM] Exception reported: Can't find "CBaseServer::ProcessConnectionlessPacket" signature.
L 05/15/2020 - 13:19:59: [SM] Blaming: server_redirect.smx
L 05/15/2020 - 13:19:59: [SM] Call stack trace:
L 05/15/2020 - 13:19:59: [SM]   [0] SetFailState
L 05/15/2020 - 13:19:59: [SM]   [1] Line 24, server_redirect/redirect.sp::SetupDhooks
L 05/15/2020 - 13:19:59: [SM]   [2] Line 184, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\server_redirect.sp::OnPluginStart
L 05/15/2020 - 13:19:59: [SM]   [4] ServerCommandEx
L 05/15/2020 - 13:19:59: [SM]   [5] Line 402, D:\builds\build-sourcemod-msvc12\windows-1.10\build\plugins\basecommands.sp::Command_Rcon

**Comment by GAMMACASE** [comment]
Use version from master branch, and verify gamedata file, as it seems to be missing.

**Comment by Nanozke** [comment]
The same thing, unfortunately.

**Comment by GAMMACASE** [comment]
Errors tells that you aren't using version from master branch and you don't have valid gamedata file, so please recheck everything.

**Comment by Nanozke** [comment]
Masterbranch from ServerRedirect or something else?

**Comment by GAMMACASE** [comment]
Yes.

**Comment by Nanozke** [comment]
I defs downloaded masterbranch.... ive just done it again. same thing.

**Comment by GAMMACASE** [comment]
By master branch I mean you need to compile it yourself from master branch, and not download from releases tab.
