### ISSUE TITLE
IP is not considered valid if it's a domain name

### ISSUE THREAD

**Issue by Sarrus1** [GAMMACASE/ServerRedirect#24]
Hello,

Since the latest update, the plugin won't load because it considers that my IP is invalid. I suspect that this is because I use a domain name instead of an actual IP adress.
Can you please remove this verification in your next release?

Thanks in advance!

PS: Here is my config:

```java
"Servers"
{
  "server1"
	{
	"ip"			"cs.tensor.fr:27015"
  "display_name"	"AWP_LEGO_ONLY n°1"
  }
  "server2"
  {
  "ip"			"cs.tensor.fr:27065"
  "display_name"	"AWP_LEGO_ONLY n°2"
  }
}
```

**Comment by GAMMACASE** [comment]
I'm aware that domain names are actually working if you add port to it, and proper support for it will come soon (can't really tell when exactly as I'm quite busy rn). But for now you can remove these lines and compile yourself, that'll do the trick, https://github.com/GAMMACASE/ServerRedirect/blob/master/addons/sourcemod/scripting/server_redirect.sp#L271-L275
