### ISSUE TITLE
StringMap.size.get error

### ISSUE THREAD

**Issue by menesakdeniz** [GAMMACASE/ServerRedirect#26]
hi i get this error what is that related with?
```
L 07/04/2020 - 17:54:33: [SM] Exception reported: Invalid Handle 0 (error 4)
L 07/04/2020 - 17:54:33: [SM] Blaming: server_redirect_core.smx
L 07/04/2020 - 17:54:33: [SM] Call stack trace:
L 07/04/2020 - 17:54:33: [SM]   [0] StringMap.Size.get
L 07/04/2020 - 17:54:33: [SM]   [1] Line 32, server_redirect/redirect.sp::ProcessConnectionlessPacket_Dhook
```

**Comment by GAMMACASE** [comment]
Don't think you use this plugin as yours is named ``server_redirect_core.smx`` where mine is ``server_redirect.smx``. In case you just renamed it then knowing version and possible way to reproduce it would be useful to know to fix this issue.

**Comment by menesakdeniz** [comment]
yes, my bad... forgot to leave gShouldReconnect allocation outside of standalone predefine...
