### ISSUE TITLE
Socket is not optional as stated in readme

### ISSUE THREAD

**Issue by orafal-dev** [GAMMACASE/ServerRedirect#30]
Tried to build `server_redirect.sp` and it fatal fails with reason:

```
server_redirect.sp(7) : fatal error 183: cannot read from file: "socket"
```

I'm assuming, `socket` is not optional anymore? Or am I doing something wrong?

**Comment by GAMMACASE** [comment]
Socket is required if you want to compile it, but at run time it's an optional dependency. You can use compiled version from release tab to get latest smx binary.
