### ISSUE TITLE
cfg/sourcemod/plugin.server_redirect.cfg not showing 

### ISSUE THREAD

**Issue by p3net** [GAMMACASE/ServerRedirect#31]
Hey, for some reason the file: cfg/sourcemod/plugin.server_redirect.cfg does not get generated.

**Comment by GAMMACASE** [comment]
It will be generated after successful plugin startup, check your error logs and make sure that plugin was loaded without any errors, then you should be able to see ``csgo/cfg/sourcemod/plugin.server_redirect.cfg`` file.

**Comment by p3net** [comment]
Hey, had some ownership issues. 

My fault.
