### ISSUE TITLE
[Improvement] IP Alias

### ISSUE THREAD

**Issue by henriquemod** [GAMMACASE/ServerRedirect#36]
Id like to suggest an improvement, in some cases (like mine) servers would communicate with each other locally in network, that would cause problems when an external client try to redirect cause plugin will redirect the client with local ip (192.168.1.x for example) what will obviously result in a timeout connection, my solution involves implementing an alias in cfg file so if the admin want to put local ip for the server be able to see the others in the same local network and put an alias ip for the plugin redirect players with the public ip address.

[Server_Redirect.zip](https://github.com/GAMMACASE/ServerRedirect/files/6156886/Server_Redirect.zip)

**Comment by GAMMACASE** [comment]
Would you be able to submit a pull request for that? Since you already made the changes.
