### ISSUE TITLE
Servers_Menu broken after recent update

### ISSUE THREAD

**Issue by Magic8Ballin** [GAMMACASE/ServerRedirect#40]
After a recent CSGO update the plugin is having issues displaying servers in the menu. (See screenshots below).

Error log:
L 11/23/2021 - 15:19:26: [SM] Exception reported: Client 13 is not connected
L 11/23/2021 - 15:19:26: [SM] Blaming: server_redirect.smx
L 11/23/2021 - 15:19:26: [SM] Call stack trace:
L 11/23/2021 - 15:19:26: [SM]   [0] GetClientUserId
L 11/23/2021 - 15:19:26: [SM]   [1] Line 604, server_redirect.sp::Servers_Menu
L 11/23/2021 - 15:19:27: Error log file session closed.

This is the only error I can find in the logs pertaining the server_redirect plugin.

![aim_deagle_simpsons_gw0000](https://user-images.githubusercontent.com/6792788/143302019-db904bda-53dd-4a07-a283-612c23ef36f5.jpg)
![aim_deagle_simpsons_gw0002](https://user-images.githubusercontent.com/6792788/143302017-b74052f9-49e1-4de7-affe-23513ee52743.jpg)

Your plugin is used heavily in ours servers @ [mygloveworks.com](https://mygloveworks.com/)
Thanks so much for creating this amazing feature inside of CSGO!

**Comment by GAMMACASE** [comment]
What version are you on? Make sure you are on the latest available version of the plugin.

**Comment by Magic8Ballin** [comment]
Wow. Yea... updating the plugin fixed it. Ha... Sorry for the mis-report. Firm handshakes for your lightning quick response and great service to the community. Happy holidays sir!

![ur-da-man-memes-com-14181390](https://user-images.githubusercontent.com/6792788/143305136-88f03d45-5ccd-4785-bb49-ce2f6922bbc1.png)
