### ISSUE TITLE
how to fix that error for reason

### ISSUE THREAD

**Issue by hanicsgo** [GAMMACASE/ServerRedirect#42]
L 01/28/2022 - 11:10:53: Info (map "de_mirage") (file "C:\steamcmd\csgo2\csgo\addons\sourcemod\logs\errors_20220128.log")
L 01/28/2022 - 11:10:53: [gv.smx] Can't add reason: , because its smaller than 3 letters. (LINE: 5)
L 01/28/2022 - 11:10:54: [server_redirect.smx] [Server Redirect] Failed to get ip for section "[ANH EM YEN BAI] PUBLIC 5v5 #1 [!ws !dao !gang !sticker]" skipping.

Well how can i fix this

**Comment by GAMMACASE** [comment]
Please, provide the full config that was used too, otherwise I wont be able to help.

**Comment by hanicsgo** [comment]
"Servers"
{
	Server entry key, each server should be under it's own key
	"server1"
	{
		"ip"			"anhemyenbai.ddns.net:27005"
		"alias_ip"		"anhemyenbai.ddns.net:27005"
		"display_name"	"[ANH EM YEN BAI] PUBLIC 5v5 #1 [!ws !dao !gang !sticker]"
	}
	
	"server2"
	{
		"ip"			"anhemyenbai.ddns.net:27015"
		"display_name"	"[ANH EM YEN BAI] PUBLIC 5v5 #2 [!ws !dao !gang !sticker]"
	}
}

**Comment by GAMMACASE** [comment]
Would ask you to upload the config to some external service (like [pastebin](https://pastebin.com/)) to not lose its formatting, but you already have ``Server entry key, each server should be under it's own key`` which should be commented out.

**Comment by hanicsgo** [comment]
well its not work about me though i have dhook and socket

**Comment by hanicsgo** [comment]
btw: i fixed that tks
