### ISSUE TITLE
Problem with running

### ISSUE THREAD

**Issue by rajkodev** [GAMMACASE/ServerRedirect#7]
Hey, I commented already closed issue, and this is new one, i cannot run plugin, also get this message in server console:

`L 03/28/2020 - 13:22:23: World triggered "Round_Start"
L 03/28/2020 - 13:22:23: [SM] Exception reported: Array index out-of-bounds (index -1, limit 32)
L 03/28/2020 - 13:22:23: [SM] Blaming: server_redirect.smx
L 03/28/2020 - 13:22:23: [SM] Call stack trace:
L 03/28/2020 - 13:22:23: [SM]   [1] Line 61, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\server_redirect.sp::ServerEntry::CutIp
L 03/28/2020 - 13:22:23: [SM]   [2] Line 371, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\server_redirect.sp::UpdateServersData
L 03/28/2020 - 13:22:23: [SM]   [3] Line 311, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\server_redirect.sp::OnConfigsExecuted`

**Comment by GAMMACASE** [comment]
You have entered an invalid ip address in ``addons/sourcemod/configs/server_redirect.cfg`` file, by invalid I mean you probably **forgot to add port to server address or you have non ipv4 ip representation**. Also I found a little bug with an invalid ip address detection, so gonna fix that too, but that's only to prevent something like this, so you still need to fix your cfg file. Thanks for the report!

**Comment by rajkodev** [comment]
Hello, thanks for answering real quick.
Also I have problem when I type in console sm_servers I get message unknown command, is that because of problem with config file?

**Comment by GAMMACASE** [comment]
Yes.

**Comment by GAMMACASE** [comment]
Alright, I guess this issue is solved and I can close it, reopen it if you'll experience this issue again.
