### ISSUE TITLE
Confirmation Box

### ISSUE THREAD

**Issue by sneak-it** [GAMMACASE/ServerRedirect#9]
It would be helpful and nice to see an option to for a confirmation once you press 'Connect' - this is brand new behavior for players and they are likely to be caught off guard instantly connecting to another server.

**Comment by GAMMACASE** [comment]
Yea sure, can add cvar for that, so if server operators want to enable this behavior they can do that.

**Comment by GAMMACASE** [comment]
Alright this feature is on master branch, soon it'll be on release. If there's something wrong or it doesn't work as expected please, reopen this issue. Thanks.
